// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acct_accounts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAcctAccount = `-- name: CreateAcctAccount :one
INSERT INTO acct_accounts (account_code, account_name, account_type, line_type)
VALUES ($1, $2, $3, $4)
RETURNING id, account_code, account_name, account_type, line_type, is_active, created_at
`

type CreateAcctAccountParams struct {
	AccountCode string `json:"account_code"`
	AccountName string `json:"account_name"`
	AccountType string `json:"account_type"`
	LineType    string `json:"line_type"`
}

func (q *Queries) CreateAcctAccount(ctx context.Context, arg CreateAcctAccountParams) (AcctAccount, error) {
	row := q.db.QueryRow(ctx, createAcctAccount,
		arg.AccountCode,
		arg.AccountName,
		arg.AccountType,
		arg.LineType,
	)
	var i AcctAccount
	err := row.Scan(
		&i.ID,
		&i.AccountCode,
		&i.AccountName,
		&i.AccountType,
		&i.LineType,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getAcctAccount = `-- name: GetAcctAccount :one
SELECT id, account_code, account_name, account_type, line_type, is_active, created_at FROM acct_accounts WHERE id = $1 AND is_active = true
`

func (q *Queries) GetAcctAccount(ctx context.Context, id uuid.UUID) (AcctAccount, error) {
	row := q.db.QueryRow(ctx, getAcctAccount, id)
	var i AcctAccount
	err := row.Scan(
		&i.ID,
		&i.AccountCode,
		&i.AccountName,
		&i.AccountType,
		&i.LineType,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAcctAccounts = `-- name: ListAcctAccounts :many
SELECT id, account_code, account_name, account_type, line_type, is_active, created_at FROM acct_accounts WHERE is_active = true ORDER BY account_code
`

func (q *Queries) ListAcctAccounts(ctx context.Context) ([]AcctAccount, error) {
	rows, err := q.db.Query(ctx, listAcctAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcctAccount{}
	for rows.Next() {
		var i AcctAccount
		if err := rows.Scan(
			&i.ID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountType,
			&i.LineType,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAcctAccount = `-- name: SoftDeleteAcctAccount :one
UPDATE acct_accounts SET is_active = false WHERE id = $1 AND is_active = true RETURNING id
`

func (q *Queries) SoftDeleteAcctAccount(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteAcctAccount, id)
	err := row.Scan(&id)
	return id, err
}

const updateAcctAccount = `-- name: UpdateAcctAccount :one
UPDATE acct_accounts
SET account_name = $2, account_type = $3, line_type = $4
WHERE id = $1 AND is_active = true
RETURNING id, account_code, account_name, account_type, line_type, is_active, created_at
`

type UpdateAcctAccountParams struct {
	ID          uuid.UUID `json:"id"`
	AccountName string    `json:"account_name"`
	AccountType string    `json:"account_type"`
	LineType    string    `json:"line_type"`
}

func (q *Queries) UpdateAcctAccount(ctx context.Context, arg UpdateAcctAccountParams) (AcctAccount, error) {
	row := q.db.QueryRow(ctx, updateAcctAccount,
		arg.ID,
		arg.AccountName,
		arg.AccountType,
		arg.LineType,
	)
	var i AcctAccount
	err := row.Scan(
		&i.ID,
		&i.AccountCode,
		&i.AccountName,
		&i.AccountType,
		&i.LineType,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
