// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acct_cash_transactions.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAcctCashTransaction = `-- name: CreateAcctCashTransaction :one
INSERT INTO acct_cash_transactions (
    transaction_code, transaction_date, item_id, description,
    quantity, unit_price, amount, line_type,
    account_id, cash_account_id, outlet_id, reimbursement_batch_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, transaction_code, transaction_date, item_id, description, quantity, unit_price, amount, line_type, account_id, cash_account_id, outlet_id, reimbursement_batch_id, created_at
`

type CreateAcctCashTransactionParams struct {
	TransactionCode      string         `json:"transaction_code"`
	TransactionDate      pgtype.Date    `json:"transaction_date"`
	ItemID               pgtype.UUID    `json:"item_id"`
	Description          string         `json:"description"`
	Quantity             pgtype.Numeric `json:"quantity"`
	UnitPrice            pgtype.Numeric `json:"unit_price"`
	Amount               pgtype.Numeric `json:"amount"`
	LineType             string         `json:"line_type"`
	AccountID            uuid.UUID      `json:"account_id"`
	CashAccountID        pgtype.UUID    `json:"cash_account_id"`
	OutletID             pgtype.UUID    `json:"outlet_id"`
	ReimbursementBatchID pgtype.Text    `json:"reimbursement_batch_id"`
}

func (q *Queries) CreateAcctCashTransaction(ctx context.Context, arg CreateAcctCashTransactionParams) (AcctCashTransaction, error) {
	row := q.db.QueryRow(ctx, createAcctCashTransaction,
		arg.TransactionCode,
		arg.TransactionDate,
		arg.ItemID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.Amount,
		arg.LineType,
		arg.AccountID,
		arg.CashAccountID,
		arg.OutletID,
		arg.ReimbursementBatchID,
	)
	var i AcctCashTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionCode,
		&i.TransactionDate,
		&i.ItemID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.Amount,
		&i.LineType,
		&i.AccountID,
		&i.CashAccountID,
		&i.OutletID,
		&i.ReimbursementBatchID,
		&i.CreatedAt,
	)
	return i, err
}

const getAcctCashTransaction = `-- name: GetAcctCashTransaction :one
SELECT id, transaction_code, transaction_date, item_id, description, quantity, unit_price, amount, line_type, account_id, cash_account_id, outlet_id, reimbursement_batch_id, created_at FROM acct_cash_transactions WHERE id = $1
`

func (q *Queries) GetAcctCashTransaction(ctx context.Context, id uuid.UUID) (AcctCashTransaction, error) {
	row := q.db.QueryRow(ctx, getAcctCashTransaction, id)
	var i AcctCashTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionCode,
		&i.TransactionDate,
		&i.ItemID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.Amount,
		&i.LineType,
		&i.AccountID,
		&i.CashAccountID,
		&i.OutletID,
		&i.ReimbursementBatchID,
		&i.CreatedAt,
	)
	return i, err
}

const getLastItemPrice = `-- name: GetLastItemPrice :one
SELECT unit_price FROM acct_cash_transactions
WHERE item_id = $1
ORDER BY transaction_date DESC, created_at DESC
LIMIT 1
`

func (q *Queries) GetLastItemPrice(ctx context.Context, itemID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getLastItemPrice, itemID)
	var unit_price pgtype.Numeric
	err := row.Scan(&unit_price)
	return unit_price, err
}

const getNextTransactionCode = `-- name: GetNextTransactionCode :one
SELECT COALESCE(MAX(transaction_code), 'PCS000000')::text AS max_code
FROM acct_cash_transactions
`

func (q *Queries) GetNextTransactionCode(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getNextTransactionCode)
	var max_code string
	err := row.Scan(&max_code)
	return max_code, err
}

const listAcctCashTransactions = `-- name: ListAcctCashTransactions :many
SELECT id, transaction_code, transaction_date, item_id, description, quantity, unit_price, amount, line_type, account_id, cash_account_id, outlet_id, reimbursement_batch_id, created_at FROM acct_cash_transactions
WHERE
    ($3::date IS NULL OR transaction_date >= $3) AND
    ($4::date IS NULL OR transaction_date <= $4) AND
    ($5::text IS NULL OR line_type = $5) AND
    ($6::uuid IS NULL OR account_id = $6) AND
    ($7::uuid IS NULL OR cash_account_id = $7) AND
    ($8::uuid IS NULL OR outlet_id = $8)
ORDER BY transaction_date DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListAcctCashTransactionsParams struct {
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	LineType      pgtype.Text `json:"line_type"`
	AccountID     pgtype.UUID `json:"account_id"`
	CashAccountID pgtype.UUID `json:"cash_account_id"`
	OutletID      pgtype.UUID `json:"outlet_id"`
}

func (q *Queries) ListAcctCashTransactions(ctx context.Context, arg ListAcctCashTransactionsParams) ([]AcctCashTransaction, error) {
	rows, err := q.db.Query(ctx, listAcctCashTransactions,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
		arg.LineType,
		arg.AccountID,
		arg.CashAccountID,
		arg.OutletID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcctCashTransaction{}
	for rows.Next() {
		var i AcctCashTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TransactionCode,
			&i.TransactionDate,
			&i.ItemID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.Amount,
			&i.LineType,
			&i.AccountID,
			&i.CashAccountID,
			&i.OutletID,
			&i.ReimbursementBatchID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
