// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acct_cash_accounts.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAcctCashAccount = `-- name: CreateAcctCashAccount :one
INSERT INTO acct_cash_accounts (cash_account_code, cash_account_name, bank_name, ownership)
VALUES ($1, $2, $3, $4)
RETURNING id, cash_account_code, cash_account_name, bank_name, ownership, is_active, created_at
`

type CreateAcctCashAccountParams struct {
	CashAccountCode string      `json:"cash_account_code"`
	CashAccountName string      `json:"cash_account_name"`
	BankName        pgtype.Text `json:"bank_name"`
	Ownership       string      `json:"ownership"`
}

func (q *Queries) CreateAcctCashAccount(ctx context.Context, arg CreateAcctCashAccountParams) (AcctCashAccount, error) {
	row := q.db.QueryRow(ctx, createAcctCashAccount,
		arg.CashAccountCode,
		arg.CashAccountName,
		arg.BankName,
		arg.Ownership,
	)
	var i AcctCashAccount
	err := row.Scan(
		&i.ID,
		&i.CashAccountCode,
		&i.CashAccountName,
		&i.BankName,
		&i.Ownership,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getAcctCashAccount = `-- name: GetAcctCashAccount :one
SELECT id, cash_account_code, cash_account_name, bank_name, ownership, is_active, created_at FROM acct_cash_accounts WHERE id = $1 AND is_active = true
`

func (q *Queries) GetAcctCashAccount(ctx context.Context, id uuid.UUID) (AcctCashAccount, error) {
	row := q.db.QueryRow(ctx, getAcctCashAccount, id)
	var i AcctCashAccount
	err := row.Scan(
		&i.ID,
		&i.CashAccountCode,
		&i.CashAccountName,
		&i.BankName,
		&i.Ownership,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAcctCashAccounts = `-- name: ListAcctCashAccounts :many
SELECT id, cash_account_code, cash_account_name, bank_name, ownership, is_active, created_at FROM acct_cash_accounts WHERE is_active = true ORDER BY cash_account_code
`

func (q *Queries) ListAcctCashAccounts(ctx context.Context) ([]AcctCashAccount, error) {
	rows, err := q.db.Query(ctx, listAcctCashAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcctCashAccount{}
	for rows.Next() {
		var i AcctCashAccount
		if err := rows.Scan(
			&i.ID,
			&i.CashAccountCode,
			&i.CashAccountName,
			&i.BankName,
			&i.Ownership,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAcctCashAccount = `-- name: SoftDeleteAcctCashAccount :one
UPDATE acct_cash_accounts SET is_active = false WHERE id = $1 AND is_active = true RETURNING id
`

func (q *Queries) SoftDeleteAcctCashAccount(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteAcctCashAccount, id)
	err := row.Scan(&id)
	return id, err
}

const updateAcctCashAccount = `-- name: UpdateAcctCashAccount :one
UPDATE acct_cash_accounts
SET cash_account_name = $2, bank_name = $3, ownership = $4
WHERE id = $1 AND is_active = true
RETURNING id, cash_account_code, cash_account_name, bank_name, ownership, is_active, created_at
`

type UpdateAcctCashAccountParams struct {
	ID              uuid.UUID   `json:"id"`
	CashAccountName string      `json:"cash_account_name"`
	BankName        pgtype.Text `json:"bank_name"`
	Ownership       string      `json:"ownership"`
}

func (q *Queries) UpdateAcctCashAccount(ctx context.Context, arg UpdateAcctCashAccountParams) (AcctCashAccount, error) {
	row := q.db.QueryRow(ctx, updateAcctCashAccount,
		arg.ID,
		arg.CashAccountName,
		arg.BankName,
		arg.Ownership,
	)
	var i AcctCashAccount
	err := row.Scan(
		&i.ID,
		&i.CashAccountCode,
		&i.CashAccountName,
		&i.BankName,
		&i.Ownership,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
