// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (outlet_id, name, description, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, outlet_id, name, description, sort_order, is_active, created_at
`

type CreateCategoryParams struct {
	OutletID    uuid.UUID   `json:"outlet_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.OutletID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, outlet_id, name, description, sort_order, is_active, created_at FROM categories WHERE id = $1 AND outlet_id = $2 AND is_active = true
`

type GetCategoryParams struct {
	ID       uuid.UUID `json:"id"`
	OutletID uuid.UUID `json:"outlet_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.OutletID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listCategoriesByOutlet = `-- name: ListCategoriesByOutlet :many
SELECT id, outlet_id, name, description, sort_order, is_active, created_at FROM categories WHERE outlet_id = $1 AND is_active = true ORDER BY sort_order, name
`

func (q *Queries) ListCategoriesByOutlet(ctx context.Context, outletID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByOutlet, outletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :one
UPDATE categories SET is_active = false WHERE id = $1 AND outlet_id = $2 AND is_active = true RETURNING id
`

type SoftDeleteCategoryParams struct {
	ID       uuid.UUID `json:"id"`
	OutletID uuid.UUID `json:"outlet_id"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteCategory, arg.ID, arg.OutletID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $1, description = $2, sort_order = $3
WHERE id = $4 AND outlet_id = $5 AND is_active = true
RETURNING id, outlet_id, name, description, sort_order, is_active, created_at
`

type UpdateCategoryParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	ID          uuid.UUID   `json:"id"`
	OutletID    uuid.UUID   `json:"outlet_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.ID,
		arg.OutletID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
