// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: combos.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createComboItem = `-- name: CreateComboItem :one
INSERT INTO combo_items (combo_id, product_id, quantity, sort_order)
VALUES ($1, $2, $3, $4) RETURNING id, combo_id, product_id, quantity, sort_order
`

type CreateComboItemParams struct {
	ComboID   uuid.UUID `json:"combo_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) CreateComboItem(ctx context.Context, arg CreateComboItemParams) (ComboItem, error) {
	row := q.db.QueryRow(ctx, createComboItem,
		arg.ComboID,
		arg.ProductID,
		arg.Quantity,
		arg.SortOrder,
	)
	var i ComboItem
	err := row.Scan(
		&i.ID,
		&i.ComboID,
		&i.ProductID,
		&i.Quantity,
		&i.SortOrder,
	)
	return i, err
}

const deleteComboItem = `-- name: DeleteComboItem :execrows
DELETE FROM combo_items WHERE id = $1 AND combo_id = $2
`

type DeleteComboItemParams struct {
	ID      uuid.UUID `json:"id"`
	ComboID uuid.UUID `json:"combo_id"`
}

func (q *Queries) DeleteComboItem(ctx context.Context, arg DeleteComboItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComboItem, arg.ID, arg.ComboID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getComboItem = `-- name: GetComboItem :one
SELECT id, combo_id, product_id, quantity, sort_order FROM combo_items WHERE id = $1 AND combo_id = $2
`

type GetComboItemParams struct {
	ID      uuid.UUID `json:"id"`
	ComboID uuid.UUID `json:"combo_id"`
}

func (q *Queries) GetComboItem(ctx context.Context, arg GetComboItemParams) (ComboItem, error) {
	row := q.db.QueryRow(ctx, getComboItem, arg.ID, arg.ComboID)
	var i ComboItem
	err := row.Scan(
		&i.ID,
		&i.ComboID,
		&i.ProductID,
		&i.Quantity,
		&i.SortOrder,
	)
	return i, err
}

const listComboItemsByCombo = `-- name: ListComboItemsByCombo :many

SELECT id, combo_id, product_id, quantity, sort_order FROM combo_items WHERE combo_id = $1 ORDER BY sort_order, id
`

// Combo Items
func (q *Queries) ListComboItemsByCombo(ctx context.Context, comboID uuid.UUID) ([]ComboItem, error) {
	rows, err := q.db.Query(ctx, listComboItemsByCombo, comboID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComboItem{}
	for rows.Next() {
		var i ComboItem
		if err := rows.Scan(
			&i.ID,
			&i.ComboID,
			&i.ProductID,
			&i.Quantity,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
