// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          uuid.UUID   `json:"id"`
	OutletID    uuid.UUID   `json:"outlet_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
}

type ComboItem struct {
	ID        uuid.UUID `json:"id"`
	ComboID   uuid.UUID `json:"combo_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	SortOrder int32     `json:"sort_order"`
}

type Customer struct {
	ID        uuid.UUID   `json:"id"`
	OutletID  uuid.UUID   `json:"outlet_id"`
	Name      string      `json:"name"`
	Phone     string      `json:"phone"`
	Email     pgtype.Text `json:"email"`
	Notes     pgtype.Text `json:"notes"`
	IsActive  bool        `json:"is_active"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Modifier struct {
	ID              uuid.UUID      `json:"id"`
	ModifierGroupID uuid.UUID      `json:"modifier_group_id"`
	Name            string         `json:"name"`
	Price           pgtype.Numeric `json:"price"`
	IsActive        bool           `json:"is_active"`
	SortOrder       int32          `json:"sort_order"`
}

type ModifierGroup struct {
	ID        uuid.UUID   `json:"id"`
	ProductID uuid.UUID   `json:"product_id"`
	Name      string      `json:"name"`
	MinSelect int32       `json:"min_select"`
	MaxSelect pgtype.Int4 `json:"max_select"`
	IsActive  bool        `json:"is_active"`
	SortOrder int32       `json:"sort_order"`
}

type Order struct {
	ID               uuid.UUID          `json:"id"`
	OutletID         uuid.UUID          `json:"outlet_id"`
	OrderNumber      string             `json:"order_number"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	OrderType        string             `json:"order_type"`
	Status           string             `json:"status"`
	TableNumber      pgtype.Text        `json:"table_number"`
	Notes            pgtype.Text        `json:"notes"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountType     pgtype.Text        `json:"discount_type"`
	DiscountValue    pgtype.Numeric     `json:"discount_value"`
	DiscountAmount   pgtype.Numeric     `json:"discount_amount"`
	TaxAmount        pgtype.Numeric     `json:"tax_amount"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	CateringDate     pgtype.Timestamptz `json:"catering_date"`
	CateringStatus   pgtype.Text        `json:"catering_status"`
	CateringDpAmount pgtype.Numeric     `json:"catering_dp_amount"`
	DeliveryPlatform pgtype.Text        `json:"delivery_platform"`
	DeliveryAddress  pgtype.Text        `json:"delivery_address"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type OrderItem struct {
	ID             uuid.UUID      `json:"id"`
	OrderID        uuid.UUID      `json:"order_id"`
	ProductID      uuid.UUID      `json:"product_id"`
	VariantID      pgtype.UUID    `json:"variant_id"`
	Quantity       int32          `json:"quantity"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	DiscountType   pgtype.Text    `json:"discount_type"`
	DiscountValue  pgtype.Numeric `json:"discount_value"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	Notes          pgtype.Text    `json:"notes"`
	Status         string         `json:"status"`
	Station        pgtype.Text    `json:"station"`
}

type OrderItemModifier struct {
	ID          uuid.UUID      `json:"id"`
	OrderItemID uuid.UUID      `json:"order_item_id"`
	ModifierID  uuid.UUID      `json:"modifier_id"`
	Quantity    int32          `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
}

type Outlet struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Address   pgtype.Text `json:"address"`
	Phone     pgtype.Text `json:"phone"`
	IsActive  bool        `json:"is_active"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Payment struct {
	ID              uuid.UUID      `json:"id"`
	OrderID         uuid.UUID      `json:"order_id"`
	PaymentMethod   string         `json:"payment_method"`
	Amount          pgtype.Numeric `json:"amount"`
	Status          string         `json:"status"`
	ReferenceNumber pgtype.Text    `json:"reference_number"`
	AmountReceived  pgtype.Numeric `json:"amount_received"`
	ChangeAmount    pgtype.Numeric `json:"change_amount"`
	ProcessedBy     uuid.UUID      `json:"processed_by"`
	ProcessedAt     time.Time      `json:"processed_at"`
}

type Product struct {
	ID              uuid.UUID      `json:"id"`
	OutletID        uuid.UUID      `json:"outlet_id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Name            string         `json:"name"`
	Description     pgtype.Text    `json:"description"`
	BasePrice       pgtype.Numeric `json:"base_price"`
	ImageUrl        pgtype.Text    `json:"image_url"`
	Station         pgtype.Text    `json:"station"`
	PreparationTime pgtype.Int4    `json:"preparation_time"`
	IsCombo         bool           `json:"is_combo"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID   `json:"id"`
	OutletID       uuid.UUID   `json:"outlet_id"`
	Email          string      `json:"email"`
	HashedPassword string      `json:"hashed_password"`
	FullName       string      `json:"full_name"`
	Role           string      `json:"role"`
	Pin            pgtype.Text `json:"pin"`
	IsActive       bool        `json:"is_active"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type Variant struct {
	ID              uuid.UUID      `json:"id"`
	VariantGroupID  uuid.UUID      `json:"variant_group_id"`
	Name            string         `json:"name"`
	PriceAdjustment pgtype.Numeric `json:"price_adjustment"`
	IsActive        bool           `json:"is_active"`
	SortOrder       int32          `json:"sort_order"`
}

type VariantGroup struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"product_id"`
	Name       string    `json:"name"`
	IsRequired bool      `json:"is_required"`
	IsActive   bool      `json:"is_active"`
	SortOrder  int32     `json:"sort_order"`
}
