// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AcctAccount struct {
	ID          uuid.UUID `json:"id"`
	AccountCode string    `json:"account_code"`
	AccountName string    `json:"account_name"`
	AccountType string    `json:"account_type"`
	LineType    string    `json:"line_type"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
}

type AcctCashAccount struct {
	ID              uuid.UUID   `json:"id"`
	CashAccountCode string      `json:"cash_account_code"`
	CashAccountName string      `json:"cash_account_name"`
	BankName        pgtype.Text `json:"bank_name"`
	Ownership       string      `json:"ownership"`
	IsActive        bool        `json:"is_active"`
	CreatedAt       time.Time   `json:"created_at"`
}

type AcctCashTransaction struct {
	ID                   uuid.UUID      `json:"id"`
	TransactionCode      string         `json:"transaction_code"`
	TransactionDate      pgtype.Date    `json:"transaction_date"`
	ItemID               pgtype.UUID    `json:"item_id"`
	Description          string         `json:"description"`
	Quantity             pgtype.Numeric `json:"quantity"`
	UnitPrice            pgtype.Numeric `json:"unit_price"`
	Amount               pgtype.Numeric `json:"amount"`
	LineType             string         `json:"line_type"`
	AccountID            uuid.UUID      `json:"account_id"`
	CashAccountID        pgtype.UUID    `json:"cash_account_id"`
	OutletID             pgtype.UUID    `json:"outlet_id"`
	ReimbursementBatchID pgtype.Text    `json:"reimbursement_batch_id"`
	CreatedAt            time.Time      `json:"created_at"`
}

type AcctItem struct {
	ID           uuid.UUID      `json:"id"`
	ItemCode     string         `json:"item_code"`
	ItemName     string         `json:"item_name"`
	ItemCategory string         `json:"item_category"`
	Unit         string         `json:"unit"`
	IsInventory  bool           `json:"is_inventory"`
	IsActive     bool           `json:"is_active"`
	AveragePrice pgtype.Numeric `json:"average_price"`
	LastPrice    pgtype.Numeric `json:"last_price"`
	ForHpp       pgtype.Numeric `json:"for_hpp"`
	Keywords     string         `json:"keywords"`
	CreatedAt    time.Time      `json:"created_at"`
}

type AcctPayrollEntry struct {
	ID            uuid.UUID          `json:"id"`
	PayrollDate   pgtype.Date        `json:"payroll_date"`
	PeriodType    string             `json:"period_type"`
	PeriodRef     pgtype.Text        `json:"period_ref"`
	EmployeeName  string             `json:"employee_name"`
	GrossPay      pgtype.Numeric     `json:"gross_pay"`
	PaymentMethod string             `json:"payment_method"`
	CashAccountID uuid.UUID          `json:"cash_account_id"`
	OutletID      pgtype.UUID        `json:"outlet_id"`
	PostedAt      pgtype.Timestamptz `json:"posted_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type AcctReimbursementRequest struct {
	ID          uuid.UUID          `json:"id"`
	BatchID     pgtype.Text        `json:"batch_id"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	ItemID      pgtype.UUID        `json:"item_id"`
	Description string             `json:"description"`
	Qty         pgtype.Numeric     `json:"qty"`
	UnitPrice   pgtype.Numeric     `json:"unit_price"`
	Amount      pgtype.Numeric     `json:"amount"`
	LineType    string             `json:"line_type"`
	AccountID   uuid.UUID          `json:"account_id"`
	Status      string             `json:"status"`
	Requester   string             `json:"requester"`
	ReceiptLink pgtype.Text        `json:"receipt_link"`
	PostedAt    pgtype.Timestamptz `json:"posted_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type AcctSalesDailySummary struct {
	ID             uuid.UUID          `json:"id"`
	SalesDate      pgtype.Date        `json:"sales_date"`
	Channel        string             `json:"channel"`
	PaymentMethod  string             `json:"payment_method"`
	GrossSales     pgtype.Numeric     `json:"gross_sales"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	NetSales       pgtype.Numeric     `json:"net_sales"`
	CashAccountID  uuid.UUID          `json:"cash_account_id"`
	OutletID       pgtype.UUID        `json:"outlet_id"`
	Source         string             `json:"source"`
	CreatedAt      time.Time          `json:"created_at"`
	PostedAt       pgtype.Timestamptz `json:"posted_at"`
}

type Category struct {
	ID          uuid.UUID   `json:"id"`
	OutletID    uuid.UUID   `json:"outlet_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
}

type ComboItem struct {
	ID        uuid.UUID `json:"id"`
	ComboID   uuid.UUID `json:"combo_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	SortOrder int32     `json:"sort_order"`
}

type Customer struct {
	ID        uuid.UUID   `json:"id"`
	OutletID  uuid.UUID   `json:"outlet_id"`
	Name      string      `json:"name"`
	Phone     string      `json:"phone"`
	Email     pgtype.Text `json:"email"`
	Notes     pgtype.Text `json:"notes"`
	IsActive  bool        `json:"is_active"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Modifier struct {
	ID              uuid.UUID      `json:"id"`
	ModifierGroupID uuid.UUID      `json:"modifier_group_id"`
	Name            string         `json:"name"`
	Price           pgtype.Numeric `json:"price"`
	IsActive        bool           `json:"is_active"`
	SortOrder       int32          `json:"sort_order"`
}

type ModifierGroup struct {
	ID        uuid.UUID   `json:"id"`
	ProductID uuid.UUID   `json:"product_id"`
	Name      string      `json:"name"`
	MinSelect int32       `json:"min_select"`
	MaxSelect pgtype.Int4 `json:"max_select"`
	IsActive  bool        `json:"is_active"`
	SortOrder int32       `json:"sort_order"`
}

type Order struct {
	ID               uuid.UUID          `json:"id"`
	OutletID         uuid.UUID          `json:"outlet_id"`
	OrderNumber      string             `json:"order_number"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	OrderType        string             `json:"order_type"`
	Status           string             `json:"status"`
	TableNumber      pgtype.Text        `json:"table_number"`
	Notes            pgtype.Text        `json:"notes"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountType     pgtype.Text        `json:"discount_type"`
	DiscountValue    pgtype.Numeric     `json:"discount_value"`
	DiscountAmount   pgtype.Numeric     `json:"discount_amount"`
	TaxAmount        pgtype.Numeric     `json:"tax_amount"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	CateringDate     pgtype.Timestamptz `json:"catering_date"`
	CateringStatus   pgtype.Text        `json:"catering_status"`
	CateringDpAmount pgtype.Numeric     `json:"catering_dp_amount"`
	DeliveryPlatform pgtype.Text        `json:"delivery_platform"`
	DeliveryAddress  pgtype.Text        `json:"delivery_address"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type OrderItem struct {
	ID             uuid.UUID      `json:"id"`
	OrderID        uuid.UUID      `json:"order_id"`
	ProductID      uuid.UUID      `json:"product_id"`
	VariantID      pgtype.UUID    `json:"variant_id"`
	Quantity       int32          `json:"quantity"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	DiscountType   pgtype.Text    `json:"discount_type"`
	DiscountValue  pgtype.Numeric `json:"discount_value"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	Notes          pgtype.Text    `json:"notes"`
	Status         string         `json:"status"`
	Station        pgtype.Text    `json:"station"`
}

type OrderItemModifier struct {
	ID          uuid.UUID      `json:"id"`
	OrderItemID uuid.UUID      `json:"order_item_id"`
	ModifierID  uuid.UUID      `json:"modifier_id"`
	Quantity    int32          `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
}

type Outlet struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Address   pgtype.Text `json:"address"`
	Phone     pgtype.Text `json:"phone"`
	IsActive  bool        `json:"is_active"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Payment struct {
	ID              uuid.UUID      `json:"id"`
	OrderID         uuid.UUID      `json:"order_id"`
	PaymentMethod   string         `json:"payment_method"`
	Amount          pgtype.Numeric `json:"amount"`
	Status          string         `json:"status"`
	ReferenceNumber pgtype.Text    `json:"reference_number"`
	AmountReceived  pgtype.Numeric `json:"amount_received"`
	ChangeAmount    pgtype.Numeric `json:"change_amount"`
	ProcessedBy     uuid.UUID      `json:"processed_by"`
	ProcessedAt     time.Time      `json:"processed_at"`
}

type Product struct {
	ID              uuid.UUID      `json:"id"`
	OutletID        uuid.UUID      `json:"outlet_id"`
	CategoryID      uuid.UUID      `json:"category_id"`
	Name            string         `json:"name"`
	Description     pgtype.Text    `json:"description"`
	BasePrice       pgtype.Numeric `json:"base_price"`
	ImageUrl        pgtype.Text    `json:"image_url"`
	Station         pgtype.Text    `json:"station"`
	PreparationTime pgtype.Int4    `json:"preparation_time"`
	IsCombo         bool           `json:"is_combo"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID   `json:"id"`
	OutletID       uuid.UUID   `json:"outlet_id"`
	Email          string      `json:"email"`
	HashedPassword string      `json:"hashed_password"`
	FullName       string      `json:"full_name"`
	Role           string      `json:"role"`
	Pin            pgtype.Text `json:"pin"`
	IsActive       bool        `json:"is_active"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type Variant struct {
	ID              uuid.UUID      `json:"id"`
	VariantGroupID  uuid.UUID      `json:"variant_group_id"`
	Name            string         `json:"name"`
	PriceAdjustment pgtype.Numeric `json:"price_adjustment"`
	IsActive        bool           `json:"is_active"`
	SortOrder       int32          `json:"sort_order"`
}

type VariantGroup struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"product_id"`
	Name       string    `json:"name"`
	IsRequired bool      `json:"is_required"`
	IsActive   bool      `json:"is_active"`
	SortOrder  int32     `json:"sort_order"`
}
