// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modifiers.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createModifier = `-- name: CreateModifier :one
INSERT INTO modifiers (modifier_group_id, name, price, sort_order)
VALUES ($1, $2, $3, $4) RETURNING id, modifier_group_id, name, price, is_active, sort_order
`

type CreateModifierParams struct {
	ModifierGroupID uuid.UUID      `json:"modifier_group_id"`
	Name            string         `json:"name"`
	Price           pgtype.Numeric `json:"price"`
	SortOrder       int32          `json:"sort_order"`
}

func (q *Queries) CreateModifier(ctx context.Context, arg CreateModifierParams) (Modifier, error) {
	row := q.db.QueryRow(ctx, createModifier,
		arg.ModifierGroupID,
		arg.Name,
		arg.Price,
		arg.SortOrder,
	)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.ModifierGroupID,
		&i.Name,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const createModifierGroup = `-- name: CreateModifierGroup :one
INSERT INTO modifier_groups (product_id, name, min_select, max_select, sort_order)
VALUES ($1, $2, $3, $4, $5) RETURNING id, product_id, name, min_select, max_select, is_active, sort_order
`

type CreateModifierGroupParams struct {
	ProductID uuid.UUID   `json:"product_id"`
	Name      string      `json:"name"`
	MinSelect int32       `json:"min_select"`
	MaxSelect pgtype.Int4 `json:"max_select"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreateModifierGroup(ctx context.Context, arg CreateModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRow(ctx, createModifierGroup,
		arg.ProductID,
		arg.Name,
		arg.MinSelect,
		arg.MaxSelect,
		arg.SortOrder,
	)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.MinSelect,
		&i.MaxSelect,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const getModifierGroup = `-- name: GetModifierGroup :one
SELECT id, product_id, name, min_select, max_select, is_active, sort_order FROM modifier_groups WHERE id = $1 AND product_id = $2 AND is_active = true
`

type GetModifierGroupParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) GetModifierGroup(ctx context.Context, arg GetModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRow(ctx, getModifierGroup, arg.ID, arg.ProductID)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.MinSelect,
		&i.MaxSelect,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const listModifierGroupsByProduct = `-- name: ListModifierGroupsByProduct :many

SELECT id, product_id, name, min_select, max_select, is_active, sort_order FROM modifier_groups WHERE product_id = $1 AND is_active = true ORDER BY sort_order, name
`

// Modifier Groups
func (q *Queries) ListModifierGroupsByProduct(ctx context.Context, productID uuid.UUID) ([]ModifierGroup, error) {
	rows, err := q.db.Query(ctx, listModifierGroupsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModifierGroup{}
	for rows.Next() {
		var i ModifierGroup
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.MinSelect,
			&i.MaxSelect,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifiersByGroup = `-- name: ListModifiersByGroup :many

SELECT id, modifier_group_id, name, price, is_active, sort_order FROM modifiers WHERE modifier_group_id = $1 AND is_active = true ORDER BY sort_order, name
`

// Modifiers
func (q *Queries) ListModifiersByGroup(ctx context.Context, modifierGroupID uuid.UUID) ([]Modifier, error) {
	rows, err := q.db.Query(ctx, listModifiersByGroup, modifierGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Modifier{}
	for rows.Next() {
		var i Modifier
		if err := rows.Scan(
			&i.ID,
			&i.ModifierGroupID,
			&i.Name,
			&i.Price,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteModifier = `-- name: SoftDeleteModifier :one
UPDATE modifiers SET is_active = false WHERE id = $1 AND modifier_group_id = $2 AND is_active = true RETURNING id
`

type SoftDeleteModifierParams struct {
	ID              uuid.UUID `json:"id"`
	ModifierGroupID uuid.UUID `json:"modifier_group_id"`
}

func (q *Queries) SoftDeleteModifier(ctx context.Context, arg SoftDeleteModifierParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteModifier, arg.ID, arg.ModifierGroupID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteModifierGroup = `-- name: SoftDeleteModifierGroup :one
UPDATE modifier_groups SET is_active = false WHERE id = $1 AND product_id = $2 AND is_active = true RETURNING id
`

type SoftDeleteModifierGroupParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) SoftDeleteModifierGroup(ctx context.Context, arg SoftDeleteModifierGroupParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteModifierGroup, arg.ID, arg.ProductID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateModifier = `-- name: UpdateModifier :one
UPDATE modifiers SET name = $1, price = $2, sort_order = $3
WHERE id = $4 AND modifier_group_id = $5 AND is_active = true RETURNING id, modifier_group_id, name, price, is_active, sort_order
`

type UpdateModifierParams struct {
	Name            string         `json:"name"`
	Price           pgtype.Numeric `json:"price"`
	SortOrder       int32          `json:"sort_order"`
	ID              uuid.UUID      `json:"id"`
	ModifierGroupID uuid.UUID      `json:"modifier_group_id"`
}

func (q *Queries) UpdateModifier(ctx context.Context, arg UpdateModifierParams) (Modifier, error) {
	row := q.db.QueryRow(ctx, updateModifier,
		arg.Name,
		arg.Price,
		arg.SortOrder,
		arg.ID,
		arg.ModifierGroupID,
	)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.ModifierGroupID,
		&i.Name,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const updateModifierGroup = `-- name: UpdateModifierGroup :one
UPDATE modifier_groups SET name = $1, min_select = $2, max_select = $3, sort_order = $4
WHERE id = $5 AND product_id = $6 AND is_active = true RETURNING id, product_id, name, min_select, max_select, is_active, sort_order
`

type UpdateModifierGroupParams struct {
	Name      string      `json:"name"`
	MinSelect int32       `json:"min_select"`
	MaxSelect pgtype.Int4 `json:"max_select"`
	SortOrder int32       `json:"sort_order"`
	ID        uuid.UUID   `json:"id"`
	ProductID uuid.UUID   `json:"product_id"`
}

func (q *Queries) UpdateModifierGroup(ctx context.Context, arg UpdateModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRow(ctx, updateModifierGroup,
		arg.Name,
		arg.MinSelect,
		arg.MaxSelect,
		arg.SortOrder,
		arg.ID,
		arg.ProductID,
	)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.MinSelect,
		&i.MaxSelect,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}
