// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders SET status = 'CANCELLED', updated_at = now()
WHERE id = $1 AND outlet_id = $2 AND status NOT IN ('COMPLETED', 'CANCELLED')
RETURNING id, outlet_id, order_number, customer_id, order_type, status, table_number, notes, subtotal, discount_type, discount_value, discount_amount, tax_amount, total_amount, catering_date, catering_status, catering_dp_amount, delivery_platform, delivery_address, created_by, created_at, updated_at, completed_at
`

type CancelOrderParams struct {
	ID       uuid.UUID `json:"id"`
	OutletID uuid.UUID `json:"outlet_id"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, arg.ID, arg.OutletID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderType,
		&i.Status,
		&i.TableNumber,
		&i.Notes,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.CateringDate,
		&i.CateringStatus,
		&i.CateringDpAmount,
		&i.DeliveryPlatform,
		&i.DeliveryAddress,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countOrderItems = `-- name: CountOrderItems :one
SELECT COUNT(*) FROM order_items WHERE order_id = $1
`

func (q *Queries) CountOrderItems(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderItems, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    outlet_id, order_number, customer_id, order_type, table_number, notes,
    subtotal, discount_type, discount_value, discount_amount, tax_amount, total_amount,
    catering_date, catering_status, catering_dp_amount,
    delivery_platform, delivery_address, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18
) RETURNING id, outlet_id, order_number, customer_id, order_type, status, table_number, notes, subtotal, discount_type, discount_value, discount_amount, tax_amount, total_amount, catering_date, catering_status, catering_dp_amount, delivery_platform, delivery_address, created_by, created_at, updated_at, completed_at
`

type CreateOrderParams struct {
	OutletID         uuid.UUID          `json:"outlet_id"`
	OrderNumber      string             `json:"order_number"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	OrderType        OrderType          `json:"order_type"`
	TableNumber      pgtype.Text        `json:"table_number"`
	Notes            pgtype.Text        `json:"notes"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountType     NullDiscountType   `json:"discount_type"`
	DiscountValue    pgtype.Numeric     `json:"discount_value"`
	DiscountAmount   pgtype.Numeric     `json:"discount_amount"`
	TaxAmount        pgtype.Numeric     `json:"tax_amount"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	CateringDate     pgtype.Timestamptz `json:"catering_date"`
	CateringStatus   NullCateringStatus `json:"catering_status"`
	CateringDpAmount pgtype.Numeric     `json:"catering_dp_amount"`
	DeliveryPlatform pgtype.Text        `json:"delivery_platform"`
	DeliveryAddress  pgtype.Text        `json:"delivery_address"`
	CreatedBy        uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OutletID,
		arg.OrderNumber,
		arg.CustomerID,
		arg.OrderType,
		arg.TableNumber,
		arg.Notes,
		arg.Subtotal,
		arg.DiscountType,
		arg.DiscountValue,
		arg.DiscountAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.CateringDate,
		arg.CateringStatus,
		arg.CateringDpAmount,
		arg.DeliveryPlatform,
		arg.DeliveryAddress,
		arg.CreatedBy,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderType,
		&i.Status,
		&i.TableNumber,
		&i.Notes,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.CateringDate,
		&i.CateringStatus,
		&i.CateringDpAmount,
		&i.DeliveryPlatform,
		&i.DeliveryAddress,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, product_id, variant_id, quantity, unit_price,
    discount_type, discount_value, discount_amount, subtotal,
    notes, station
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11
) RETURNING id, order_id, product_id, variant_id, quantity, unit_price, discount_type, discount_value, discount_amount, subtotal, notes, status, station
`

type CreateOrderItemParams struct {
	OrderID        uuid.UUID          `json:"order_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	VariantID      pgtype.UUID        `json:"variant_id"`
	Quantity       int32              `json:"quantity"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	DiscountType   NullDiscountType   `json:"discount_type"`
	DiscountValue  pgtype.Numeric     `json:"discount_value"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	Subtotal       pgtype.Numeric     `json:"subtotal"`
	Notes          pgtype.Text        `json:"notes"`
	Station        NullKitchenStation `json:"station"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.VariantID,
		arg.Quantity,
		arg.UnitPrice,
		arg.DiscountType,
		arg.DiscountValue,
		arg.DiscountAmount,
		arg.Subtotal,
		arg.Notes,
		arg.Station,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.Subtotal,
		&i.Notes,
		&i.Status,
		&i.Station,
	)
	return i, err
}

const createOrderItemModifier = `-- name: CreateOrderItemModifier :one
INSERT INTO order_item_modifiers (
    order_item_id, modifier_id, quantity, unit_price
) VALUES ($1, $2, $3, $4) RETURNING id, order_item_id, modifier_id, quantity, unit_price
`

type CreateOrderItemModifierParams struct {
	OrderItemID uuid.UUID      `json:"order_item_id"`
	ModifierID  uuid.UUID      `json:"modifier_id"`
	Quantity    int32          `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
}

func (q *Queries) CreateOrderItemModifier(ctx context.Context, arg CreateOrderItemModifierParams) (OrderItemModifier, error) {
	row := q.db.QueryRow(ctx, createOrderItemModifier,
		arg.OrderItemID,
		arg.ModifierID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i OrderItemModifier
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.ModifierID,
		&i.Quantity,
		&i.UnitPrice,
	)
	return i, err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items WHERE id = $1 AND order_id = $2
`

type DeleteOrderItemParams struct {
	ID      uuid.UUID `json:"id"`
	OrderID uuid.UUID `json:"order_id"`
}

func (q *Queries) DeleteOrderItem(ctx context.Context, arg DeleteOrderItemParams) error {
	_, err := q.db.Exec(ctx, deleteOrderItem, arg.ID, arg.OrderID)
	return err
}

const getModifierForOrder = `-- name: GetModifierForOrder :one
SELECT m.id, m.price, mg.product_id
FROM modifiers m
JOIN modifier_groups mg ON mg.id = m.modifier_group_id
WHERE m.id = $1 AND m.is_active = true AND mg.is_active = true
`

type GetModifierForOrderRow struct {
	ID        uuid.UUID      `json:"id"`
	Price     pgtype.Numeric `json:"price"`
	ProductID uuid.UUID      `json:"product_id"`
}

func (q *Queries) GetModifierForOrder(ctx context.Context, id uuid.UUID) (GetModifierForOrderRow, error) {
	row := q.db.QueryRow(ctx, getModifierForOrder, id)
	var i GetModifierForOrderRow
	err := row.Scan(&i.ID, &i.Price, &i.ProductID)
	return i, err
}

const getNextOrderNumber = `-- name: GetNextOrderNumber :one
SELECT COALESCE(MAX(CAST(SPLIT_PART(order_number, '-', 2) AS INT)), 0) + 1 AS next_number
FROM orders
WHERE outlet_id = $1 AND created_at::date = CURRENT_DATE
`

func (q *Queries) GetNextOrderNumber(ctx context.Context, outletID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextOrderNumber, outletID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, outlet_id, order_number, customer_id, order_type, status, table_number, notes, subtotal, discount_type, discount_value, discount_amount, tax_amount, total_amount, catering_date, catering_status, catering_dp_amount, delivery_platform, delivery_address, created_by, created_at, updated_at, completed_at FROM orders WHERE id = $1 AND outlet_id = $2
`

type GetOrderParams struct {
	ID       uuid.UUID `json:"id"`
	OutletID uuid.UUID `json:"outlet_id"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.OutletID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderType,
		&i.Status,
		&i.TableNumber,
		&i.Notes,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.CateringDate,
		&i.CateringStatus,
		&i.CateringDpAmount,
		&i.DeliveryPlatform,
		&i.DeliveryAddress,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOrderItem = `-- name: GetOrderItem :one
SELECT id, order_id, product_id, variant_id, quantity, unit_price, discount_type, discount_value, discount_amount, subtotal, notes, status, station FROM order_items WHERE id = $1 AND order_id = $2
`

type GetOrderItemParams struct {
	ID      uuid.UUID `json:"id"`
	OrderID uuid.UUID `json:"order_id"`
}

func (q *Queries) GetOrderItem(ctx context.Context, arg GetOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItem, arg.ID, arg.OrderID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.Subtotal,
		&i.Notes,
		&i.Status,
		&i.Station,
	)
	return i, err
}

const getProductForOrder = `-- name: GetProductForOrder :one
SELECT id, outlet_id, base_price, station FROM products
WHERE id = $1 AND outlet_id = $2 AND is_active = true
`

type GetProductForOrderParams struct {
	ID       uuid.UUID `json:"id"`
	OutletID uuid.UUID `json:"outlet_id"`
}

type GetProductForOrderRow struct {
	ID        uuid.UUID          `json:"id"`
	OutletID  uuid.UUID          `json:"outlet_id"`
	BasePrice pgtype.Numeric     `json:"base_price"`
	Station   NullKitchenStation `json:"station"`
}

func (q *Queries) GetProductForOrder(ctx context.Context, arg GetProductForOrderParams) (GetProductForOrderRow, error) {
	row := q.db.QueryRow(ctx, getProductForOrder, arg.ID, arg.OutletID)
	var i GetProductForOrderRow
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.BasePrice,
		&i.Station,
	)
	return i, err
}

const getVariantForOrder = `-- name: GetVariantForOrder :one
SELECT v.id, v.variant_group_id, v.price_adjustment, vg.product_id
FROM variants v
JOIN variant_groups vg ON vg.id = v.variant_group_id
WHERE v.id = $1 AND v.is_active = true AND vg.is_active = true
`

type GetVariantForOrderRow struct {
	ID              uuid.UUID      `json:"id"`
	VariantGroupID  uuid.UUID      `json:"variant_group_id"`
	PriceAdjustment pgtype.Numeric `json:"price_adjustment"`
	ProductID       uuid.UUID      `json:"product_id"`
}

func (q *Queries) GetVariantForOrder(ctx context.Context, id uuid.UUID) (GetVariantForOrderRow, error) {
	row := q.db.QueryRow(ctx, getVariantForOrder, id)
	var i GetVariantForOrderRow
	err := row.Scan(
		&i.ID,
		&i.VariantGroupID,
		&i.PriceAdjustment,
		&i.ProductID,
	)
	return i, err
}

const listActiveOrders = `-- name: ListActiveOrders :many
SELECT o.id, o.outlet_id, o.order_number, o.customer_id, o.order_type, o.status, o.table_number, o.notes, o.subtotal, o.discount_type, o.discount_value, o.discount_amount, o.tax_amount, o.total_amount, o.catering_date, o.catering_status, o.catering_dp_amount, o.delivery_platform, o.delivery_address, o.created_by, o.created_at, o.updated_at, o.completed_at,
       COALESCE(
         (SELECT SUM(p.amount) FROM payments p WHERE p.order_id = o.id AND p.status = 'COMPLETED'),
         0
       )::decimal(12,2) AS amount_paid
FROM orders o
WHERE o.outlet_id = $1
  AND (
    o.status IN ('NEW', 'PREPARING', 'READY')
    OR (o.order_type = 'CATERING' AND o.catering_status IN ('BOOKED', 'DP_PAID'))
  )
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveOrdersParams struct {
	OutletID uuid.UUID `json:"outlet_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListActiveOrdersRow struct {
	ID               uuid.UUID          `json:"id"`
	OutletID         uuid.UUID          `json:"outlet_id"`
	OrderNumber      string             `json:"order_number"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	OrderType        OrderType          `json:"order_type"`
	Status           OrderStatus        `json:"status"`
	TableNumber      pgtype.Text        `json:"table_number"`
	Notes            pgtype.Text        `json:"notes"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountType     NullDiscountType   `json:"discount_type"`
	DiscountValue    pgtype.Numeric     `json:"discount_value"`
	DiscountAmount   pgtype.Numeric     `json:"discount_amount"`
	TaxAmount        pgtype.Numeric     `json:"tax_amount"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	CateringDate     pgtype.Timestamptz `json:"catering_date"`
	CateringStatus   NullCateringStatus `json:"catering_status"`
	CateringDpAmount pgtype.Numeric     `json:"catering_dp_amount"`
	DeliveryPlatform pgtype.Text        `json:"delivery_platform"`
	DeliveryAddress  pgtype.Text        `json:"delivery_address"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	AmountPaid       pgtype.Numeric     `json:"amount_paid"`
}

func (q *Queries) ListActiveOrders(ctx context.Context, arg ListActiveOrdersParams) ([]ListActiveOrdersRow, error) {
	rows, err := q.db.Query(ctx, listActiveOrders, arg.OutletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveOrdersRow{}
	for rows.Next() {
		var i ListActiveOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.OrderNumber,
			&i.CustomerID,
			&i.OrderType,
			&i.Status,
			&i.TableNumber,
			&i.Notes,
			&i.Subtotal,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountAmount,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.CateringDate,
			&i.CateringStatus,
			&i.CateringDpAmount,
			&i.DeliveryPlatform,
			&i.DeliveryAddress,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.AmountPaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemModifiersByOrderItem = `-- name: ListOrderItemModifiersByOrderItem :many
SELECT id, order_item_id, modifier_id, quantity, unit_price FROM order_item_modifiers WHERE order_item_id = $1 ORDER BY id
`

func (q *Queries) ListOrderItemModifiersByOrderItem(ctx context.Context, orderItemID uuid.UUID) ([]OrderItemModifier, error) {
	rows, err := q.db.Query(ctx, listOrderItemModifiersByOrderItem, orderItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItemModifier{}
	for rows.Next() {
		var i OrderItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.OrderItemID,
			&i.ModifierID,
			&i.Quantity,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT id, order_id, product_id, variant_id, quantity, unit_price, discount_type, discount_value, discount_amount, subtotal, notes, status, station FROM order_items WHERE order_id = $1 ORDER BY id
`

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.VariantID,
			&i.Quantity,
			&i.UnitPrice,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountAmount,
			&i.Subtotal,
			&i.Notes,
			&i.Status,
			&i.Station,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, outlet_id, order_number, customer_id, order_type, status, table_number, notes, subtotal, discount_type, discount_value, discount_amount, tax_amount, total_amount, catering_date, catering_status, catering_dp_amount, delivery_platform, delivery_address, created_by, created_at, updated_at, completed_at FROM orders
WHERE outlet_id = $1
  AND ($4::order_status IS NULL OR status = $4::order_status)
  AND ($5::order_type IS NULL OR order_type = $5::order_type)
  AND ($6::timestamptz IS NULL OR created_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR created_at < $7::timestamptz + interval '1 day')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersParams struct {
	OutletID  uuid.UUID          `json:"outlet_id"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
	Status    NullOrderStatus    `json:"status"`
	OrderType NullOrderType      `json:"order_type"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.OutletID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.OrderType,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.OrderNumber,
			&i.CustomerID,
			&i.OrderType,
			&i.Status,
			&i.TableNumber,
			&i.Notes,
			&i.Subtotal,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountAmount,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.CateringDate,
			&i.CateringStatus,
			&i.CateringDpAmount,
			&i.DeliveryPlatform,
			&i.DeliveryAddress,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByOrder = `-- name: ListPaymentsByOrder :many
SELECT id, order_id, payment_method, amount, status, reference_number, amount_received, change_amount, processed_by, processed_at FROM payments WHERE order_id = $1 ORDER BY processed_at
`

func (q *Queries) ListPaymentsByOrder(ctx context.Context, orderID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PaymentMethod,
			&i.Amount,
			&i.Status,
			&i.ReferenceNumber,
			&i.AmountReceived,
			&i.ChangeAmount,
			&i.ProcessedBy,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItem = `-- name: UpdateOrderItem :one
UPDATE order_items SET
    quantity = $3,
    notes = $4,
    discount_amount = $5,
    subtotal = $6
WHERE id = $1 AND order_id = $2
RETURNING id, order_id, product_id, variant_id, quantity, unit_price, discount_type, discount_value, discount_amount, subtotal, notes, status, station
`

type UpdateOrderItemParams struct {
	ID             uuid.UUID      `json:"id"`
	OrderID        uuid.UUID      `json:"order_id"`
	Quantity       int32          `json:"quantity"`
	Notes          pgtype.Text    `json:"notes"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItem,
		arg.ID,
		arg.OrderID,
		arg.Quantity,
		arg.Notes,
		arg.DiscountAmount,
		arg.Subtotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.Subtotal,
		&i.Notes,
		&i.Status,
		&i.Station,
	)
	return i, err
}

const updateOrderItemStatus = `-- name: UpdateOrderItemStatus :one
UPDATE order_items SET
    status = $3
WHERE id = $1 AND order_id = $2
RETURNING id, order_id, product_id, variant_id, quantity, unit_price, discount_type, discount_value, discount_amount, subtotal, notes, status, station
`

type UpdateOrderItemStatusParams struct {
	ID      uuid.UUID       `json:"id"`
	OrderID uuid.UUID       `json:"order_id"`
	Status  OrderItemStatus `json:"status"`
}

func (q *Queries) UpdateOrderItemStatus(ctx context.Context, arg UpdateOrderItemStatusParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItemStatus, arg.ID, arg.OrderID, arg.Status)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.Subtotal,
		&i.Notes,
		&i.Status,
		&i.Station,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders SET status = $3,
    completed_at = CASE WHEN $3 = 'COMPLETED' THEN now() ELSE completed_at END,
    updated_at = now()
WHERE id = $1 AND outlet_id = $2 AND status = $4
RETURNING id, outlet_id, order_number, customer_id, order_type, status, table_number, notes, subtotal, discount_type, discount_value, discount_amount, tax_amount, total_amount, catering_date, catering_status, catering_dp_amount, delivery_platform, delivery_address, created_by, created_at, updated_at, completed_at
`

type UpdateOrderStatusParams struct {
	ID       uuid.UUID   `json:"id"`
	OutletID uuid.UUID   `json:"outlet_id"`
	Status   OrderStatus `json:"status"`
	Status_2 OrderStatus `json:"status_2"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus,
		arg.ID,
		arg.OutletID,
		arg.Status,
		arg.Status_2,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderType,
		&i.Status,
		&i.TableNumber,
		&i.Notes,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.CateringDate,
		&i.CateringStatus,
		&i.CateringDpAmount,
		&i.DeliveryPlatform,
		&i.DeliveryAddress,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateOrderTotals = `-- name: UpdateOrderTotals :one
UPDATE orders SET
    subtotal = (SELECT COALESCE(SUM(oi.subtotal), 0) FROM order_items oi WHERE oi.order_id = $1),
    discount_amount = CASE
        WHEN discount_type = 'PERCENTAGE' THEN
            (SELECT COALESCE(SUM(oi.subtotal), 0) FROM order_items oi WHERE oi.order_id = $1) * discount_value / 100
        WHEN discount_type = 'FIXED_AMOUNT' THEN LEAST(discount_value, (SELECT COALESCE(SUM(oi.subtotal), 0) FROM order_items oi WHERE oi.order_id = $1))
        ELSE 0
    END,
    total_amount = (SELECT COALESCE(SUM(oi.subtotal), 0) FROM order_items oi WHERE oi.order_id = $1)
        - CASE
            WHEN discount_type = 'PERCENTAGE' THEN
                (SELECT COALESCE(SUM(oi.subtotal), 0) FROM order_items oi WHERE oi.order_id = $1) * discount_value / 100
            WHEN discount_type = 'FIXED_AMOUNT' THEN LEAST(discount_value, (SELECT COALESCE(SUM(oi.subtotal), 0) FROM order_items oi WHERE oi.order_id = $1))
            ELSE 0
        END
        + tax_amount,
    updated_at = now()
WHERE id = $1
RETURNING id, outlet_id, order_number, customer_id, order_type, status, table_number, notes, subtotal, discount_type, discount_value, discount_amount, tax_amount, total_amount, catering_date, catering_status, catering_dp_amount, delivery_platform, delivery_address, created_by, created_at, updated_at, completed_at
`

func (q *Queries) UpdateOrderTotals(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderTotals, orderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderType,
		&i.Status,
		&i.TableNumber,
		&i.Notes,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.CateringDate,
		&i.CateringStatus,
		&i.CateringDpAmount,
		&i.DeliveryPlatform,
		&i.DeliveryAddress,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
