// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outlets.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOutlet = `-- name: CreateOutlet :one
INSERT INTO outlets (name, address, phone)
VALUES ($1, $2, $3)
RETURNING id, name, address, phone, is_active, created_at, updated_at
`

type CreateOutletParams struct {
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
}

func (q *Queries) CreateOutlet(ctx context.Context, arg CreateOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, createOutlet, arg.Name, arg.Address, arg.Phone)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutlet = `-- name: GetOutlet :one
SELECT id, name, address, phone, is_active, created_at, updated_at FROM outlets WHERE id = $1 AND is_active = true
`

func (q *Queries) GetOutlet(ctx context.Context, id uuid.UUID) (Outlet, error) {
	row := q.db.QueryRow(ctx, getOutlet, id)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOutlets = `-- name: ListOutlets :many
SELECT id, name, address, phone, is_active, created_at, updated_at FROM outlets WHERE is_active = true ORDER BY name
`

func (q *Queries) ListOutlets(ctx context.Context) ([]Outlet, error) {
	rows, err := q.db.Query(ctx, listOutlets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outlet{}
	for rows.Next() {
		var i Outlet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOutlet = `-- name: SoftDeleteOutlet :exec
UPDATE outlets SET is_active = false WHERE id = $1
`

func (q *Queries) SoftDeleteOutlet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteOutlet, id)
	return err
}

const updateOutlet = `-- name: UpdateOutlet :one
UPDATE outlets SET name = $1, address = $2, phone = $3
WHERE id = $4 AND is_active = true
RETURNING id, name, address, phone, is_active, created_at, updated_at
`

type UpdateOutletParams struct {
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateOutlet(ctx context.Context, arg UpdateOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, updateOutlet,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.ID,
	)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
