// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (outlet_id, category_id, name, description, base_price, image_url, station, preparation_time, is_combo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, outlet_id, category_id, name, description, base_price, image_url, station, preparation_time, is_combo, is_active, created_at, updated_at
`

type CreateProductParams struct {
	OutletID        uuid.UUID          `json:"outlet_id"`
	CategoryID      uuid.UUID          `json:"category_id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	BasePrice       pgtype.Numeric     `json:"base_price"`
	ImageUrl        pgtype.Text        `json:"image_url"`
	Station         NullKitchenStation `json:"station"`
	PreparationTime pgtype.Int4        `json:"preparation_time"`
	IsCombo         bool               `json:"is_combo"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.OutletID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.BasePrice,
		arg.ImageUrl,
		arg.Station,
		arg.PreparationTime,
		arg.IsCombo,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.ImageUrl,
		&i.Station,
		&i.PreparationTime,
		&i.IsCombo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, outlet_id, category_id, name, description, base_price, image_url, station, preparation_time, is_combo, is_active, created_at, updated_at FROM products WHERE id = $1 AND outlet_id = $2 AND is_active = true
`

type GetProductParams struct {
	ID       uuid.UUID `json:"id"`
	OutletID uuid.UUID `json:"outlet_id"`
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.OutletID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.ImageUrl,
		&i.Station,
		&i.PreparationTime,
		&i.IsCombo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductsByOutlet = `-- name: ListProductsByOutlet :many
SELECT id, outlet_id, category_id, name, description, base_price, image_url, station, preparation_time, is_combo, is_active, created_at, updated_at FROM products WHERE outlet_id = $1 AND is_active = true ORDER BY name
`

func (q *Queries) ListProductsByOutlet(ctx context.Context, outletID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByOutlet, outletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.BasePrice,
			&i.ImageUrl,
			&i.Station,
			&i.PreparationTime,
			&i.IsCombo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :one
UPDATE products SET is_active = false, updated_at = now() WHERE id = $1 AND outlet_id = $2 AND is_active = true RETURNING id
`

type SoftDeleteProductParams struct {
	ID       uuid.UUID `json:"id"`
	OutletID uuid.UUID `json:"outlet_id"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteProduct, arg.ID, arg.OutletID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET category_id = $1, name = $2, description = $3, base_price = $4, image_url = $5, station = $6, preparation_time = $7, is_combo = $8, updated_at = now()
WHERE id = $9 AND outlet_id = $10 AND is_active = true
RETURNING id, outlet_id, category_id, name, description, base_price, image_url, station, preparation_time, is_combo, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	CategoryID      uuid.UUID          `json:"category_id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	BasePrice       pgtype.Numeric     `json:"base_price"`
	ImageUrl        pgtype.Text        `json:"image_url"`
	Station         NullKitchenStation `json:"station"`
	PreparationTime pgtype.Int4        `json:"preparation_time"`
	IsCombo         bool               `json:"is_combo"`
	ID              uuid.UUID          `json:"id"`
	OutletID        uuid.UUID          `json:"outlet_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.BasePrice,
		arg.ImageUrl,
		arg.Station,
		arg.PreparationTime,
		arg.IsCombo,
		arg.ID,
		arg.OutletID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.ImageUrl,
		&i.Station,
		&i.PreparationTime,
		&i.IsCombo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
