// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, outlet_id, email, hashed_password, full_name, role, pin, is_active, created_at, updated_at FROM users WHERE email = $1 AND is_active = true
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.Role,
		&i.Pin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, outlet_id, email, hashed_password, full_name, role, pin, is_active, created_at, updated_at FROM users WHERE id = $1 AND is_active = true
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.Role,
		&i.Pin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOutletAndPin = `-- name: GetUserByOutletAndPin :one
SELECT id, outlet_id, email, hashed_password, full_name, role, pin, is_active, created_at, updated_at FROM users WHERE outlet_id = $1 AND pin = $2 AND is_active = true
`

type GetUserByOutletAndPinParams struct {
	OutletID uuid.UUID   `json:"outlet_id"`
	Pin      pgtype.Text `json:"pin"`
}

func (q *Queries) GetUserByOutletAndPin(ctx context.Context, arg GetUserByOutletAndPinParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOutletAndPin, arg.OutletID, arg.Pin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.Role,
		&i.Pin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
