// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variants.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVariant = `-- name: CreateVariant :one
INSERT INTO variants (variant_group_id, name, price_adjustment, sort_order)
VALUES ($1, $2, $3, $4) RETURNING id, variant_group_id, name, price_adjustment, is_active, sort_order
`

type CreateVariantParams struct {
	VariantGroupID  uuid.UUID      `json:"variant_group_id"`
	Name            string         `json:"name"`
	PriceAdjustment pgtype.Numeric `json:"price_adjustment"`
	SortOrder       int32          `json:"sort_order"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.VariantGroupID,
		arg.Name,
		arg.PriceAdjustment,
		arg.SortOrder,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.VariantGroupID,
		&i.Name,
		&i.PriceAdjustment,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const createVariantGroup = `-- name: CreateVariantGroup :one
INSERT INTO variant_groups (product_id, name, is_required, sort_order)
VALUES ($1, $2, $3, $4) RETURNING id, product_id, name, is_required, is_active, sort_order
`

type CreateVariantGroupParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	Name       string    `json:"name"`
	IsRequired bool      `json:"is_required"`
	SortOrder  int32     `json:"sort_order"`
}

func (q *Queries) CreateVariantGroup(ctx context.Context, arg CreateVariantGroupParams) (VariantGroup, error) {
	row := q.db.QueryRow(ctx, createVariantGroup,
		arg.ProductID,
		arg.Name,
		arg.IsRequired,
		arg.SortOrder,
	)
	var i VariantGroup
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.IsRequired,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const getVariantGroup = `-- name: GetVariantGroup :one
SELECT id, product_id, name, is_required, is_active, sort_order FROM variant_groups WHERE id = $1 AND product_id = $2 AND is_active = true
`

type GetVariantGroupParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) GetVariantGroup(ctx context.Context, arg GetVariantGroupParams) (VariantGroup, error) {
	row := q.db.QueryRow(ctx, getVariantGroup, arg.ID, arg.ProductID)
	var i VariantGroup
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.IsRequired,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const listVariantGroupsByProduct = `-- name: ListVariantGroupsByProduct :many

SELECT id, product_id, name, is_required, is_active, sort_order FROM variant_groups WHERE product_id = $1 AND is_active = true ORDER BY sort_order, name
`

// Variant Groups
func (q *Queries) ListVariantGroupsByProduct(ctx context.Context, productID uuid.UUID) ([]VariantGroup, error) {
	rows, err := q.db.Query(ctx, listVariantGroupsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariantGroup{}
	for rows.Next() {
		var i VariantGroup
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.IsRequired,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByGroup = `-- name: ListVariantsByGroup :many

SELECT id, variant_group_id, name, price_adjustment, is_active, sort_order FROM variants WHERE variant_group_id = $1 AND is_active = true ORDER BY sort_order, name
`

// Variants
func (q *Queries) ListVariantsByGroup(ctx context.Context, variantGroupID uuid.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariantsByGroup, variantGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variant{}
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.VariantGroupID,
			&i.Name,
			&i.PriceAdjustment,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVariant = `-- name: SoftDeleteVariant :one
UPDATE variants SET is_active = false WHERE id = $1 AND variant_group_id = $2 AND is_active = true RETURNING id
`

type SoftDeleteVariantParams struct {
	ID             uuid.UUID `json:"id"`
	VariantGroupID uuid.UUID `json:"variant_group_id"`
}

func (q *Queries) SoftDeleteVariant(ctx context.Context, arg SoftDeleteVariantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteVariant, arg.ID, arg.VariantGroupID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteVariantGroup = `-- name: SoftDeleteVariantGroup :one
UPDATE variant_groups SET is_active = false WHERE id = $1 AND product_id = $2 AND is_active = true RETURNING id
`

type SoftDeleteVariantGroupParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) SoftDeleteVariantGroup(ctx context.Context, arg SoftDeleteVariantGroupParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteVariantGroup, arg.ID, arg.ProductID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE variants SET name = $1, price_adjustment = $2, sort_order = $3
WHERE id = $4 AND variant_group_id = $5 AND is_active = true RETURNING id, variant_group_id, name, price_adjustment, is_active, sort_order
`

type UpdateVariantParams struct {
	Name            string         `json:"name"`
	PriceAdjustment pgtype.Numeric `json:"price_adjustment"`
	SortOrder       int32          `json:"sort_order"`
	ID              uuid.UUID      `json:"id"`
	VariantGroupID  uuid.UUID      `json:"variant_group_id"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.Name,
		arg.PriceAdjustment,
		arg.SortOrder,
		arg.ID,
		arg.VariantGroupID,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.VariantGroupID,
		&i.Name,
		&i.PriceAdjustment,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const updateVariantGroup = `-- name: UpdateVariantGroup :one
UPDATE variant_groups SET name = $1, is_required = $2, sort_order = $3
WHERE id = $4 AND product_id = $5 AND is_active = true RETURNING id, product_id, name, is_required, is_active, sort_order
`

type UpdateVariantGroupParams struct {
	Name       string    `json:"name"`
	IsRequired bool      `json:"is_required"`
	SortOrder  int32     `json:"sort_order"`
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"product_id"`
}

func (q *Queries) UpdateVariantGroup(ctx context.Context, arg UpdateVariantGroupParams) (VariantGroup, error) {
	row := q.db.QueryRow(ctx, updateVariantGroup,
		arg.Name,
		arg.IsRequired,
		arg.SortOrder,
		arg.ID,
		arg.ProductID,
	)
	var i VariantGroup
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.IsRequired,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}
